---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ template "hello-covantis.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "hello-covantis.name" . }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ template "hello-covantis.name" . }}
    spec:
      containers:
      - image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        name: hello-covantis
        resources: {}
        ports:
          - name: container-port
            containerPort: 9090
            protocol: TCP

