apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: finesse-frontend
  annotations:
    run.googleapis.com/launch-stage: BETA 
    labels:
    cloud.googleapis.com/location: europe-central2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 451.0.1
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: mxjwjyftnp
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: europe-central2-docker.pkg.dev/fourkeys-386218/finesse-frontend/finesse-frontend:d630f9d6e24ed2798719625d38e66b49b936aa9f
        ports:
        - containerPort: 8080
        env:
        - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
          value: "http://localhost:4317"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      - image: europe-central2-docker.pkg.dev/fourkeys-386218/run-otel/otel-collector-metrics
        name: collector
        startupProbe:
          httpGet:
            path: /
            port: 13133
      serviceAccountName: 29322109009-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://finesse-frontend-uterycxntq-lm.a.run.app
  conditions:
  - lastTransitionTime: '2023-10-24T16:39:50.466946Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2023-10-24T16:39:39.592907Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2023-10-24T16:39:50.528056Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: finesse-frontend-00009-srv
  latestReadyRevisionName: finesse-frontend-00009-srv
  observedGeneration: 9
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: finesse-frontend-00009-srv
  url: https://finesse-frontend-uterycxntq-lm.a.run.app
