apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-webserver
  name: hello-webserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-webserver
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-webserver
    spec:
      containers:
      - image: ds4tech/webserver:0.0.3
        name: hello-webserver
        resources: {}
        ports:
          - name: container-port
            containerPort: 9090
            protocol: TCP
        env:
        - name: ENV
          value: "Kubernetes"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-webserver
  name: hello-webserver
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: webserver
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: hello-webserver
