apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: finesse-frontend
  name: finesse-frontend
  # namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finesse-frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: finesse-frontend
    spec:
      containers:
      - image: ds4tech/finesse-frontend:0.0.4
        name: finesse-frontend
        resources: {}
        ports:
          - name: container-port
            containerPort: 8080
            protocol: TCP
        env:
        - name: ENV
          value: "Kubernetes"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: finesse-frontend-svc
  name: finesse-frontend-svc
  # namespace: default
spec:
  type: ClusterIP
  ports:
  - name: finesse
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: finesse-frontend
