---
# Default values for sladashboard.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  repository: ds4tech/covantis
  tag: 0.0.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


replicas: 1

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: 2
    memory: 4Gi 

nodeSelector: {}

tolerations: []

affinity: {}



