apiVersion: cache.example.com/v1alpha1
kind: Webserver
metadata:
  labels:
    app.kubernetes.io/name: webserver
    app.kubernetes.io/instance: webserver-sample
    app.kubernetes.io/part-of: operator-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator-go
  name: webserver-sample
spec:
  size: 2

  # replicas: 1
  # selector:
  #   matchLabels:
  #     app: hello-webserver
  # strategy: {}
  # template:
  #   metadata:
  #     labels:
  #       app: hello-webserver
  #   spec:
  #     containers:
  #     - image: ds4tech/webserver:0.0.3
  #       name: hello-webserver
  #       resources: {}
  #       ports:
  #         - name: container-port
  #           containerPort: 9090
  #           protocol: TCP
  #       env:
  #       - name: ENV
  #         value: "Operator"

