
name: Deploy to Cloud Run

on:
  [push]

jobs:
  build:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
      deployments: write

    runs-on: ubuntu-latest
    steps: 
      - name: Triger Deployment Event
        uses: altinukshini/deployment-action@releases/v1
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: dev

      - name: Update deployment status (success)
        if: success()
        uses: altinukshini/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          # target_url: http://my-app-url.com
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      # - name: Deploy to Cloud Run
      #   uses: google-github-actions/deploy-cloudrun@v1.0.2
      