
name: Deploy to Cloud Run

on:
  [push]

jobs:
  build:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
      deployments: write

    runs-on: ubuntu-latest
    steps: 
      - name: Triger Deployment Event
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: dev

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          # token: "${{ secrets.WIF_PROVIDER }}"
          # target_url: https://finesse-frontend-uterycxntq-lm.a.run.app
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'

      # - name: Deploy to Cloud Run
      #   uses: google-github-actions/deploy-cloudrun@v1.0.2
      