
name: Triger Deployment Events

on:
  push:
    branches:
      - main
      - 'releases/**'
  workflow_dispatch:
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
      deployments: write

    runs-on: ubuntu-latest
    steps: 
      - name: Triger Deployment Event
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: dev

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'failure'

      # - name: Deploy to Cloud Run
      #   uses: google-github-actions/deploy-cloudrun@v1.0.2
      