
name: Deploy to Cloud Run

on:
  [push]

jobs:
  build:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
      deployments: write

    runs-on: ubuntu-latest
    steps: 
      - name: Triger Deployment Event
        uses: altinukshini/deployment-action@releases/v1
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: dev
  